services:
  - type: web
    name: sih2026-api
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CORS_ORIGINS
        value: "*"
      - key: FIRMS_MAP_KEY
        value: 51ca9bc710f3add041124d86ddbb631d
